### PR TITLE
Netty5.x Multipart Codec for Netty Contrib

### PR DESCRIPTION
**Pull request by pderop**
# Motivation

This PR is an attempt to port the current Netty 4.1.80.Final-SNAPSHOT Multipart codec to the Netty 5.0.0-Alpha5 version.

# Modifications

Mainly, bellow are the proposed changes that have been done (to be discussed :-)):

## InterfaceHttpData.java

Before this interface was extending __ReferenceCounted__ with the following methods:
```
    Int refCnt();
    ReferenceCounted retain();
    ReferenceCounted retain(int increment);
    ReferenceCounted touch();
    ReferenceCounted touch(Object hint);
    boolean release();
    boolean release(int decrement);
```
Now, the interface is now extending __Resource<HttpData>__, and the above methods are replaced by:
```
    Send<T> send();
    void close();
    boolean isAccessible();
    touch(Object hint);
```
So, we now have:
```
public interface InterfaceHttpData extends Comparable<InterfaceHttpData>, Resource<HttpData> {
    enum HttpDataType {
        Attribute, FileUpload, InternalAttribute
    }
    String getName();
    HttpDataType getHttpDataType();
}
```

### HttpData.java

The HttpData interface does not extend the __ByteBufHolder__ anymore, so, the following methods:
```
    ByteBuf content();
    ByteBufHolder copy();
    ByteBufHolder duplicate();
    ByteBufHolder retainedDuplicate();
    ByteBufHolder replace(ByteBuf content);
    ByteBufHolder retain();
    ByteBufHolder retain(int increment);
    ByteBufHolder touch();
    ByteBufHolder touch(Object hint);
```
are replaced by:
```
    Buffer content();
    HttpData copy();
    HttpData replace(Buffer content);
```

### AbstractHttpData.java

The AbstractHttpData does not extend the __AbstractReferenceCounted__ anymore. It instead extends __ResourceSupport<HttpData, AbstractHttpData>__ in order to make it easier to implement the Resource interface. A __Drop__ static inner class is now used to ensure that the __HttpData.delete()__ method is invoked when the resource is closed.

The old AbstractReferenceCounted methods have been removed:
```
    public ByteBuf content();
    protected void deallocate();
    public HttpData retain();
    public HttpData retain(int increment);
    public abstract HttpData touch();
    public abstract HttpData touch(Object hint);
```

The content can now be obtained using content() method which is now returning a Buffer:

    Buffer content();

### HttpPostMultipartRequestDecoder.java

Before, the __offer(HttpContent content)__ method was doing this check in order to possibly discard undecoded chunks:

```
        if (undecodedChunk != null && undecodedChunk.writerIndex() > discardThreshold) {
            if (undecodedChunk.refCnt() == 1) {
                // It's safe to call discardBytes() as we are the only owner of the buffer.
                undecodedChunk.discardReadBytes();
            } else {
                // There seems to be multiple references of the buffer. Let's copy the data and release the buffer to
                // ensure we can give back memory to the system.
                ByteBuf buffer = undecodedChunk.alloc().buffer(undecodedChunk.readableBytes());
                buffer.writeBytes(undecodedChunk);
                undecodedChunk.release();
                undecodedChunk = buffer;
            }
        }
```
now it is assumed that the content ownership is transferred to the MP codec, so the above code has been replaced by:
```
        if (undecodedChunk != null && undecodedChunk.writerOffset() > discardThreshold) {
            undecodedChunk.compact();
        }
```

**Note:** it may make sense to change the __offer(HttpContent content)__ signature by __offer(Send\<HttpContent\> content)__, in order to enforce the fact that the ownership is really transferred to the API. See below TODO section.

### HttpPostStandardRequestDecoder.java:

The __parseBodyAttributes__ method was using old __ByteBuf.array()__ method in order to optimize parsing of body attributes, like this:
```
    private void parseBodyAttributes() {
        if (undecodedChunk == null) {
            return;
        }
        if (!undecodedChunk.hasArray()) {
            parseBodyAttributesStandard();
            return;
        }
        SeekAheadOptimize sao = new SeekAheadOptimize(undecodedChunk);
        ...
        // use the sao to optimizing parsing of body attribytes using undecodecChunk.array()
```
So, in the porting, the optimization has been removed because the Buffer API does not provide the byte array anymore,
and only the parseBodyAttributesStandard() has been kept in the new version:
```
    private void parseBodyAttributes() {
        if (undecodedChunk == null) {
            return;
        }
        parseBodyAttributesStandard();
    }
```

However, we can probably optimize the __parseBodyAttributesStandard__ method with Cursors.

# Result

The tests are passing, the new multipart codec is now based on netty5 buffers, and does not depend anymore on ByteBuf API.

# Current status and improvements

Old multipart PRs from 4.1.80.Final-SNAPSHOT are merged, but there is still room for enhancements. I have created other PRs which can be addressed separately:

- Use cursors more appropriately  #2
- Enforce buffer ownership using Send #3
- HttpPostRequestDecoder as a Resource  #4
- AbstractMemoryHttpData performance issue when using composite buffer #6

### CODE REVIEW

**Comment by pderop** [comment]
@normanmaurer , @chrisvest ,

Hi, 

Could you please take a look at this PR ?

This PR is now functional, where the old benchmark and the old examples from 4.1.x are also ported. There are still rooms for enhancements, but I have created separate PRs which can be addressed separately (later):

- #2
- #3
- #4

thank you.

**Comment by pderop** [comment]
Merged the following PRs from 4.1 branch:

- https://github.com/netty/netty/pull/12427
- https://github.com/netty/netty/pull/12650
- https://github.com/netty/netty/pull/12664

**Comment by pderop** [comment]
@chrisvest , @normanmaurer;

Could one of you kindly review this PR please? Indeed, we have another PR in Reactor-Netty that is pending and it depends on this PR in order  reintegrate multipart using Netty5. 

This PR is proposing a variant of the old API, but I'll be happy to finalise it in case you think there are problems with the proposed API changes. Now, there is still room for enhancements, but I have created separate PRs which can be addressed separately (later):

- Use cursors more appropriately  #2
- Enforce buffer ownership using Send #3
- HttpPostRequestDecoder as a Resource  #4
- AbstractMemoryHttpData performance issue when using composite buffer #6

thanks !

**Comment by chrisvest** [comment]
@pderop I don't think we (Norman and I) have the bandwidth to help out with http multipart. I think you have the ability to merge it yourself, right? You can of course ask others in the community if you want more eyes on it.

**Comment by pderop** [comment]
@chrisvest ,

Ok, then I will see if someone else from the community would like to review this PR before I merge it.

**Comment by pderop** [comment]
The PR has been integrated in reactor-netty draft PR (https://github.com/reactor/reactor-netty/pull/2327), and from discord, there is a feedback regarding scalability of instanceof checks (I have created the #10 PR in order to investigate this a bit later).

So, In the meantime, let's merge this PR into main.

**Pull request merged**
